left_camera:
  address: 169.254.128.10
  port: 9766
  topic: camera/left
  is_depth_img: false
  fx: 320
  fy: 320
  cx: 320
  cy: 240
right_camera:
  address: 169.254.128.10
  port: 9767
  topic: camera/right
  is_depth_img: false
  fx: 320
  fy: 320
  cx: 320
  cy: 240
depth_camera:
  address: 169.254.128.10
  port: 9768
  topic: camera/depth
  is_depth_img: true
  fx: 320
  fy: 320
  cx: 320
  cy: 240
imu:
  address: 169.254.128.10
  port: 9774
  topic: data_raw
lidar:
  address: 169.254.128.10
  port: 9773
  topic: scan
att_controller:
  address: 169.254.128.21
  port: 9771
  topic: control_cmd
ground_truth:
  address: 169.254.128.10
  port: 9775
  topic: ground_truth_odom
